export ZSH="$HOME/.oh-my-zsh"
export DOTFILES="$HOME/dotfiles"

ZSH_THEME="spaceship"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

export SPACESHIP_CONFIG="$HOME/.oh-my-zsh/custom/spaceship.zsh"


