export ZSH="$HOME/.oh-my-zsh"
export DOTFILES="$HOME/dotfiles"

ZSH_THEME="spaceship"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

export SPACESHIP_CONFIG="$HOME/.oh-my-zsh/custom/spaceship.zsh"

# --- Carregar Funções Personalizadas (Autoload) ---
# O OMZ já adicionou '$ZSH/custom' ao $fpath.
# Nós adicionamos nosso novo subdiretório 'functions'.
fpath=($ZSH/custom/functions $fpath)

# Registra os nomes das funções para autoload
autoload dotfiles_bkp
# autoload mkcd   (adicione suas outras funções aqui)
# autoload extract
# --- Fim das Funções ---


